# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Project Configuration
project.name=xposed
project.android.compileSdk=35
project.android.minSdk=29
project.android.targetSdk=35
project.app.packageName=com.xicko.xposed
project.app.versionName="1.0.0"
project.app.versionCode=1
android.builtInKotlin=false
android.newDsl=false